version: '3.8'

services:
  bot:
    build: .
    container_name: restaurant_training_bot
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    ports:
      - "8000:5000"
    command: python bot.py

  admin:
    build: .
    container_name: restaurant_training_admin
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    ports:
      - "5001:5000"
    command: gunicorn --workers 3 --bind 0.0.0.0:5000 admin:app
    depends_on:
      - bot

volumes:
  data:
